### ISSUE TITLE
Perform Reload from command Line.

### ISSUE THREAD

**Issue by weswhet** [hjuutilainen/munkiadmin#100]
Is there a way to perform a reload of munki admin from the command line?

**Comment by hjuutilainen** [comment]
Unfortunately no. Shouldn't be that hard to implement though. Are you perhaps running AutoPkg and you'd like to reload the repo once it's done?

**Comment by weswhet** [comment]
Autopkg and I also wrote something for the junior admins in my shop that does all the git pulls and branches stuff and mounts the fileshare. At the end it launches munkiadmin if it's not open. Would like to add the option to auto reload it if it's open.

**Comment by hjuutilainen** [comment]
I think your best bet would be to just quit and reopen MunkiAdmin and have it open the previous repository on launch.
