### ISSUE TITLE
Description key invalid quotation marks

### ISSUE THREAD

**Issue by thomasbergmann** [hjuutilainen/munkiadmin#104]
Hi,
inserting html in the description key via MunkiAdmin converts quotation marks to some weird ones not being interpreted in package view in Managed Software Center.
Cheers
Thomas

**Comment by hjuutilainen** [comment]
Could you post an example? Is your system configured to convert standard quotes to smart quotes? MunkiAdmin should ignore those but I've seen the smart quotes cause headaches multiple times.

**Comment by thomasbergmann** [comment]
![bildschirmfoto 2015-11-11 um 16 17 11](https://cloud.githubusercontent.com/assets/5112294/11094361/b79c5dcc-888f-11e5-89bd-e6d18b328d88.png)
![bildschirmfoto 2015-11-11 um 16 16 21](https://cloud.githubusercontent.com/assets/5112294/11094364/b99cc7d8-888f-11e5-8544-ee00cfe69e9d.png)

**Comment by thomasbergmann** [comment]
But should look like this (manually edited):
![bildschirmfoto 2015-11-11 um 16 19 03](https://cloud.githubusercontent.com/assets/5112294/11094409/fd5d34bc-888f-11e5-87fb-788d485fee20.png)

**Comment by hjuutilainen** [comment]
Yep, those look like smart quotes that OS X likes to automatically use. Could you try right-clicking on the description field and see if there are settings for those. There's also a global "off switch" for smart quotes in System Preferences -> Keyboard (if I remember the place correctly).

**Comment by thomasbergmann** [comment]
Woohoo, never seen that. You are right. Disabled and it works like charm!
![bildschirmfoto 2015-11-11 um 17 02 53](https://cloud.githubusercontent.com/assets/5112294/11095591/1715512c-8896-11e5-8b17-874421ab6585.png)

**Comment by hjuutilainen** [comment]
Great!
