### ISSUE TITLE
Unavailable Packages removed from Catalog without any notification

### ISSUE THREAD

**Issue by cwastell** [hjuutilainen/munkiadmin#107]
We keep our Munki repo in git and clone the repo to our local machines when we need to make changes. Because of their size we don't keep the /pkgs/ directory in git, instead when we're working with Munki admin we'll mount a network share to the /pkgs/ directory. 

Which works great, but if we lose connectivity to the network share (thus munki admin sees /pkgs/ as empty), when saving it'll remove the references to those packages from the catalog (effectively blanking out the catalog) with no real warning. 

It'd be nice to have some sort of dialog saying that it can't access the packages when saving in munki admin.

**Comment by hjuutilainen** [comment]
Thanks for reporting. We're using a similar workflow here (but constantly without the pkgs directory). When the pkgs directory is unavailable you should check the "disable sanity checks" option in preferences which causes MunkiAdmin to run makecatalogs with the --force argument. In fact, in your case, I'd suggest keeping that option on all the time. You will get complete catalogs every time whether the actual packages are available or not.

**Comment by cwastell** [comment]
Awesome, thanks that makes sense. Didn't know that was an option, works great. 

Thanks for the response!
