### ISSUE TITLE
Saving Manifest causes makecatalogs to run.

### ISSUE THREAD

**Issue by erikng** [hjuutilainen/munkiadmin#108]
When modifying a manifest, the admin must hit the "save" button. This has the undesired effect of also running makecatalogs.

makecatalogs should only be ran if there are actual changes to pkginfo files. 

This causes additional load on the server as the e-tags are then modified.

**Comment by erikng** [comment]
Additionally, if an admin doesn't have the munki administrative tools installed, you receive an error that "makecatalogs couldn't run". The administrative tools are not needed for manifest manipulation.

**Comment by hjuutilainen** [comment]
I agree. I will add more options to configure the saving further.

Thanks for reporting. Hadn't really run into this before. We're constantly running MunkiAdmin with makecatalogs disabled since we're building the catalogs on the server side when deploying.

**Comment by hjuutilainen** [comment]
Fix for this will be included in the next release :)

![screen shot 2016-01-20 at 14 06 18](https://cloud.githubusercontent.com/assets/19357/12448499/1dbe9b4e-bf7f-11e5-9608-1d18968f6d32.png)

**Comment by erikng** [comment]
Awesome. You are a beast.

**Comment by hjuutilainen** [comment]
Finally included in a released version (1.4.2).
