### ISSUE TITLE
Property values fail to remain populated

### ISSUE THREAD

**Issue by n8felton** [hjuutilainen/munkiadmin#109]
Summary:
When entering a value for a pkginfo property and clicking **Previous** or **Next** without changing the focus of the property box to another property box first will result in the value not persisting.

Steps to Reproduce:
1. Open a pkginfo item and navigate to the **Requirements** tab.
2. Enter an **Installable condition** such as `os_vers_minor >= 7`
3. Click the **Next** button.
4. Click the **Previous** button.
5. The value you entered will be missing.

Expected Results:
The value should remain populated.

Actual Results:
The value will be lost

Notes:
If you tab and select another property field before clicking Next, the value will remain populated.

Slack conversation about this available at https://macadmins.slack.com/archives/munkiadmin/p1453403098000106

**Comment by hjuutilainen** [comment]
Thanks for opening an issue and thanks for the exceptionally well-written description! Fix will be included in the next release.
