### ISSUE TITLE
malformed manifest plist

### ISSUE THREAD

**Issue by graffaelli** [hjuutilainen/munkiadmin#110]
I've got a fresh munki install and munki admin on the latest version but when I create catalogs, assign client identifiers and then run a manual managed software update, I get the following message:

WARNING: Manifest /Library/Managed Installs/manifests/client_manifest.plist has no catalogs

When I look at the manifest directly, it looks like this: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>included_manifests</key>
        <array>
                <string>site_default</string>
        </array>
        <key>managed_installs</key>
        <array>
                <string>Firefox</string>
                <string>GoogleChrome</string>
        </array>
</dict>
</plist>
```

Though from a working munki server, it should look more like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>catalogs</key>
    <array>
        <string>testing</string>
    </array>
    <key>managed_installs</key>
    <array>
        <string>Avira Free Mac Security</string>
        <string>Firefox</string>
    </array>
</dict>
</plist>
```

It seems like the `<key>catalogs</key>` is missing for some reason. Any idea if that would be the cause fo the error?

The machine is running OS 10.11.2.

**Comment by hjuutilainen** [comment]
When you open the manifest in MunkiAdmin, have you checked any of the catalogs there? Your manifest should look something like this:

<img width="890" alt="screen shot 2016-01-29 at 8 43 07" src="https://cloud.githubusercontent.com/assets/19357/12668936/72bae95e-c664-11e5-96a3-f61b53ad3752.png">


This will result a file that looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>catalogs</key>
	<array>
		<string>production</string>
	</array>
	<key>included_manifests</key>
	<array>
		<string>some-other-manifest</string>
	</array>
</dict>
</plist>
```

**Comment by graffaelli** [comment]
I do have catalogs checked for the manifests.

~g

On Jan 28, 2016, at 22:44, Hannes Juutilainen <notifications@github.com<mailto:notifications@github.com>> wrote:


When you open the manifest in MunkiAdmin, have you checked any of the catalogs there? Your manifest should look something like this:

[screen shot 2016-01-29 at 8 43 07]<https://cloud.githubusercontent.com/assets/19357/12668936/72bae95e-c664-11e5-96a3-f61b53ad3752.png>

This will result a file that looks like this:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>catalogs</key>
    <array>
        <string>production</string>
    </array>
    <key>included_manifests</key>
    <array>
        <string>some-other-manifest</string>
    </array>
</dict>
</plist>

**Comment by hjuutilainen** [comment]
I can't reproduce this (or I don't fully understand the issue). Could write down the exact steps how you're running in to this?

**Comment by graffaelli** [comment]
I'll start from scratch and document everything. Maybe it was a bad install? Definitely strange behavior. The plist is definitely not complete. It's missing the catalog key even though that is checked in the gui. Maybe I'm missing a step. I'll be on site with this machine tomorrow and will check it out.

Thanks for your help.

-- via mobile

On Jan 30, 2016, at 05:07, Hannes Juutilainen <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this (or I don't fully understand the issue). Could write down the exact steps how you're running in to this?

-

**Comment by graffaelli** [comment]
Ok. I’ve got some more information. Here’s the setup at the outset.

Three default manifests in place:

servers
staff
site_default

Two catalogs:

testing
stable

Under the stable catalog, I have checked the box to assign/enable Firefox and Chrome.

Under the site_default manifest, I assigned the stable catalog and saved.

Then I nested the site_default manifest to both the staff and servers manifest. But I did not assign any catalog directly to the servers or staff manifest.

If I assign a client to the servers manifest, even though the site_default manifest is nested, I receive the error that the manifest has no catalogs.

If I assign a client directly to the site_default manifest, I get the proper catalog and (as long as I assign the managed applications to the manifest), I can get the applications to install.

I’m not sure if this is an issue with my Munki install or the MunkiAdmin tool. If you have any ideas, that would be great. Seems like nested manifest function is not working.

~g

On Jan 30, 2016, at 14:05, Gabriel Raffaelli <gabriel@lindegroup.com<mailto:gabriel@lindegroup.com>> wrote:

I'll start from scratch and document everything. Maybe it was a bad install? Definitely strange behavior. The plist is definitely not complete. It's missing the catalog key even though that is checked in the gui. Maybe I'm missing a step. I'll be on site with this machine tomorrow and will check it out.

Thanks for your help.

-- via mobile

On Jan 30, 2016, at 05:07, Hannes Juutilainen <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this (or I don't fully understand the issue). Could write down the exact steps how you're running in to this?

**Comment by hjuutilainen** [comment]
Ah, ok. Thanks for clearing this for me, now I understand. This is actually not an issue at all but a feature of Munki itself. The idea in a setting that you described is that you would assign a catalog in both servers and staff manifests but _not_ in the site_default catalog. The general "best practice" is to not have a catalog assigned in nested manifests at all because Munki client will use the catalog(s) defined in the very first manifest it downloads.

Taking your setup one step further, I'd recommend turning things around and using unique client identifiers. You would then have the following "machine" or "client" manifests with catalogs defined:
- client_1
- client_2
- client_3
- site_default (Munki client will fall back to this if it doesn't find a manifest)

You would also have the following "group" manifests with _no_ catalogs defined:
- servers
- staff

Each of the client manifests would use the servers or staff manifests (or both) as a nested manifest. In this setup the client manifest decides the catalog(s) to use and the group manifests decide what to install. And as a plus you can make individual changes per client if needed.

**Comment by graffaelli** [comment]
Totally makes sense. Thanks for the clarification. I completely misunderstood the purpose of nested manifests, it would seem.

I appreciate your help and your time. Extremely useful.

~g

On Feb 1, 2016, at 22:56, Hannes Juutilainen <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, ok. Thanks for clearing this for me, now I understand. This is actually not an issue at all but a feature of Munki itself. The idea in a setting that you described is that you would assign a catalog in both servers and staff manifests but not in the site_default catalog. The general "best practice" is to not have a catalog assigned in nested manifests at all because Munki client will use the catalog(s) defined in the very first manifest it downloads.

Taking your setup one step further, I'd recommend turning things around and using unique client identifiers. You would then have the following "machine" or "client" manifests with catalogs defined:

  *   client_1
  *   client_2
  *   client_3
  *   site_default (Munki client will fall back to this if it doesn't find a manifest)

You would also have the following "group" manifests with no catalogs defined:

  *   servers
  *   staff

Each of the client manifests would use the servers or staff manifests (or both) as a nested manifest. In this setup the client manifest decides the catalog(s) to use and the group manifests decide what to install. And as a plus you can make individual changes per client if needed.

**Comment by graffaelli** [comment]
Thanks for the help! I think I’ve got it. Each client has a unique identifier and a then using the ClientIdentifier plist, each client machine will have it’s own manifest to which it’s assigned. Each of those then has the default catalog.

Then, the group manifests have no catalogs but will have the assigned applications and the group manifests are then nested under the client manifest to tell munki what to actually install.

Thanks again. I thought I was going crazy but it turns out I was just turned around.

~g

On Feb 1, 2016, at 22:56, Hannes Juutilainen <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, ok. Thanks for clearing this for me, now I understand. This is actually not an issue at all but a feature of Munki itself. The idea in a setting that you described is that you would assign a catalog in both servers and staff manifests but not in the site_default catalog. The general "best practice" is to not have a catalog assigned in nested manifests at all because Munki client will use the catalog(s) defined in the very first manifest it downloads.

Taking your setup one step further, I'd recommend turning things around and using unique client identifiers. You would then have the following "machine" or "client" manifests with catalogs defined:

  *   client_1
  *   client_2
  *   client_3
  *   site_default (Munki client will fall back to this if it doesn't find a manifest)

You would also have the following "group" manifests with no catalogs defined:

  *   servers
  *   staff

Each of the client manifests would use the servers or staff manifests (or both) as a nested manifest. In this setup the client manifest decides the catalog(s) to use and the group manifests decide what to install. And as a plus you can make individual changes per client if needed.
