### ISSUE TITLE
Referencing manifest not being populated with manifest subdirectories. 

### ISSUE THREAD

**Issue by weswhet** [hjuutilainen/munkiadmin#119]
I noticed that if I move my manifests into sub manifest directories Referencing Manifests seems to break. For example: Before making changes I had all my machine and user manifests in /repo/manifests and everything was looking great.. It correctly shows the machine manifests. Picture below. 
<img width="889" alt="screen shot 2016-04-02 at 1 45 43 pm" src="https://cloud.githubusercontent.com/assets/6865785/14228910/4412db86-f8da-11e5-9d08-1015bd34d3d7.png">

As soon as I moved all machine manifests to `/repo/manifests/machines/` and `/repo/manifests/users/`. (I am actually not sure if munki supports this, its just going to help with some automation of manifests.) MunkiAdmin appears to lose the Referencing Manifests. Picture Below.. 
<img width="889" alt="screen shot 2016-04-02 at 1 38 12 pm" src="https://cloud.githubusercontent.com/assets/6865785/14228933/d1f4ec78-f8da-11e5-9a63-06a03f7190e9.png">

I hope I explained that well enough. :)

**Comment by weswhet** [comment]
oh and MunkiAdmin has been awesome with 5000+ manifests so far! :smile:

**Comment by weswhet** [comment]
Nevermind. Found out I need to give the full path to the manifest in the included manifest sectional..

**Comment by hjuutilainen** [comment]
I like these new self-closing tickets! :)
