### ISSUE TITLE
Crashes on MacOS 10.12 Siera Beta

### ISSUE THREAD

**Issue by RonaldCarter** [hjuutilainen/munkiadmin#129]
When you go to change window under MacOS 10.12 Siera Beta it crashes

**Comment by hjuutilainen** [comment]
What version of MunkiAdmin are you using? There's a new version (1.4.3) available from the releases page with some Sierra compatibility fixes. It's not yet available from the in-app update check so you'll have to download it manually.

**Comment by RonaldCarter** [comment]
I feel like an ID10T,

Thank you for that it worked fine for me with no crashes
