### ISSUE TITLE
Deleting a Package leaves behind the Uninstall Package

### ISSUE THREAD

**Issue by kevinmcox** [hjuutilainen/munkiadmin#138]
Deleting a package through MunkiAdmin leaves behind the optional uninstall package created with the --uninstallpkg flag of munkiimport.

**Comment by hjuutilainen** [comment]
Thanks for reporting! Will fix for next release.

**Comment by kevinmcox** [comment]
Sure thing, love the program, makes it so fast to edit things after I get them in the repo.
