### ISSUE TITLE
updated to 1.5 makecatalogs fails

### ISSUE THREAD

**Issue by colbrugit** [hjuutilainen/munkiadmin#143]
updated to Munki 3.0.0.3333 and installed munkiadmin 1.5
Following the error when makecatalogs is run by pressing save.

When using 1.4.3 makecatalogs runs through without problems.

2017/06/08 12:51:08:697  Starting MunkiAdmin version 1.5.0
2017/06/08 12:51:23:166  Traceback (most recent call last):
  File "/usr/local/munki/makecatalogs", line 357, in <module>
2017/06/08 12:51:23:166  main()
  File "/usr/local/munki/makecatalogs", line 354, in main
    makecatalogs(repo, options)
  File "/usr/local/munki/makecatalogs", line 256, in makecatalogs
    print_utf8("Adding %s to %s..." % (pkginfo_ref, catalogname))
  File "/usr/local/munki/munkilib/cliutils.py", line 118, in print_utf8
    print text.encode('UTF-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 32: ordinal not in range(128)
2017/06/08 12:51:23:463  makecatalogs exited with code 1

**Comment by hjuutilainen** [comment]
Thanks for reporting.

This error is coming from the `makecatalogs` tool and it seems to be a bit picky about filenames. In previous MunkiAdmin versions this error was just silently ignored so I think this is an improvement.

Do you get the same error when running makecatalogs from the command line (`makecatalogs -f <path_to_repo>`)? If so, what's the last filename the command prints out before crashing? Your problem file is probably the next file alphabetically.

**Comment by colbrugit** [comment]
Thanks Hannes

that helped.
I have a packed called Wine_entraine.pkg that was processed successfull.
After that packet some others processed fine too.
Because of the placement in the directory tree it was processed before of
the following file that caused the problem. Wine_entraine.dmg.
I've deleted Wine_entraine.dmg and makecatalogs ran through fine.


Now I get a bunch of warnings regarding "different case" I will work those
out.

My repo is a little messy... ;-)


2017-06-08 14:53 GMT+02:00 Hannes Juutilainen <notifications@github.com>:
