### ISSUE TITLE
Notes field in Manifest:General should be presented as a textarea

### ISSUE THREAD

**Issue by diwanicki** [hjuutilainen/munkiadmin#148]
Even though the Notes key pair is a string in the XML, the data entry in the application should allow for long-form text entry, not just be a UITextField with a larger than normal view.

re: Slack discussion June 22 2017

**Comment by hjuutilainen** [comment]
Thanks for opening an issue. This is already addressed in 984c1d478c8ed6287ed34e74dead9988b87b745c and will be included in the next release.
