### ISSUE TITLE
Clicking 'Cancel' button in Properties window does not cancel changes

### ISSUE THREAD

**Issue by flammable** [hjuutilainen/munkiadmin#151]
Steps to reproduce:

1. Open a Munki repo in MunkiAdmin.
2. Right-click on an item and open Properties.
3. Make a change. I've been able to replicate this behavior with the On Demand and Unattended Install checkboxes.
4. Click the Cancel button.

The expected behavior is that when reopening the Properties window, your changes have been reverted.  However, that does not appear to be the case - any changes made before clicking the Cancel button will persist.  If you were to click the Save button, your changes will be written to the pkginfo files.

I'm running MunkiAdmin 1.5.1 on macOS 10.12.6.  Thanks for looking into this!  Let me know if I can do additional testing or provide any more details. :)

**Comment by hjuutilainen** [comment]
Thanks for reporting this. The cancel functionality is performed using standard undo/redo and it seems that it's completely broken on 1.5.0 and 1.5.1. Will fix shortly and release a bug fix update.

**Comment by hjuutilainen** [comment]
A fix for this is included in the test build linked in issue #150 if you’d like to try it. I’ll probably release it as 1.5.2 tomorrow.

**Comment by flammable** [comment]
Thanks! I didn't have a chance to test up until now, but 1.5.2 works perfectly.

I really appreciate all of the support!  Besides Safari and Mail, MunkiAdmin is probably my most-used application at work. :)

I'll close this ticket!
