### ISSUE TITLE
Auto-update seems to fail.

### ISSUE THREAD

**Issue by thomasm2film** [hjuutilainen/munkiadmin#152]
When 1.51 was out, v 1.50 said it was on the current version.
Now running 1.51 and 1.52 is out - still does not recognise the latest version.
Thanks

**Comment by hjuutilainen** [comment]
Thanks for reporting. I was about to update the release feed couple of days ago but a major bug was reported in 1.5.1 (and 1.5.0). I decided to skip 1.5.1 completely and offer version 1.5.2 through auto-update. It should now be available.

Generally releases will first be available from GitHub releases page (where they will be picked up by AutoPkg) but I'll usually hold off a few days before updating the auto-update feed.

**Comment by thomasm2film** [comment]
Thanks!
