### ISSUE TITLE
When adding an installs array to a item, leaving item type blank errors out

### ISSUE THREAD

**Issue by WardsParadox** [hjuutilainen/munkiadmin#153]
MA will not allow you to add an installs array item to any item if you leave the package type as empty. This is a problem as there is no official key value for the default apple package type. 
#### Workflow to re-create:
1. Import installer package type item.
2. Attempt to create an installs array for this item with a package receipt.
3. Attempt to save.
4. MA will error out and will refuse to save. Even removing the "offending" installs item results in MA not saving and complaining about that installs type can not be empty.

**Comment by 0scubasteve0** [comment]
To add to this, when you click the + symbol to add a new item, and then click the - button to remove it, it will not allow you to save your changes. The error states that you must specify a package type.  Same workflow to re-create as above.

**Comment by hjuutilainen** [comment]
Thank you both for reporting. I added default values for new installs items and it seems to help. Now installs items can not be in invalid state and saved. Fix will be included in the next release.

**Comment by hjuutilainen** [comment]
Fixed in 1.6.0
