### ISSUE TITLE
Item isn't appearing in MunkiAdmin

### ISSUE THREAD

**Issue by klou** [hjuutilainen/munkiadmin#161]
Here's an odd one -- and I'm sure it worked in the past.

I just noticed that a pkginfo (Thunderbird_cfg-60.0.0.plist) isn't available in MunkiAdmin.  I don't think that it's because of the underscore because I have other items with underscores that DO appear.  The item is still active and appears in makecatalogs:

> Adding pkgsinfo/Mozilla/MailMerge-4.6.1.plist to production...
> Adding pkgsinfo/Mozilla/Thunderbird_cfg-60.0.0.plist to testing...
> Adding pkgsinfo/Mozilla/Firefox-52.6.0.plist to testing...
> 

However, ALL instances of Thunderbird_cfg do not show.  It's odd.

Pkginfo:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>_metadata</key>
	<dict>
		<key>created_by</key>
		<string>klou</string>
		<key>creation_date</key>
		<date>2018-05-08T23:20:57Z</date>
		<key>munki_version</key>
		<string>3.2.1.3498</string>
		<key>os_version</key>
		<string>10.12.6</string>
	</dict>
	<key>autoremove</key>
	<false/>
	<key>blocking_applications</key>
	<array>
		<string>Thunderbird</string>
	</array>
	<key>catalogs</key>
	<array>
		<string>testing</string>
	</array>
	<key>category</key>
	<string>Office</string>
	<key>description</key>
	<string>Mission Control Desktop (AutoConfig) for Thunderbird</string>
	<key>developer</key>
	<string>Mozilla</string>
	<key>display_name</key>
	<string>Thunderbird_cfg</string>
	<key>installed_size</key>
	<integer>9</integer>
	<key>installer_item_hash</key>
	<string>948216a85298587604f303528d1f88efefc5e31f6aa9790a29e8650c68f4d953</string>
	<key>installer_item_location</key>
	<string>Mozilla/Thunderbird_cfg-60.0.0.pkg</string>
	<key>installer_item_size</key>
	<integer>4</integer>
	<key>minimum_os_version</key>
	<string>10.5.0</string>
	<key>name</key>
	<string>Thunderbird_cfg</string>
	<key>receipts</key>
	<array>
		<dict>
			<key>installed_size</key>
			<integer>9</integer>
			<key>packageid</key>
			<string>xxx.xxxx.Thunderbird_cfg</string>
			<key>version</key>
			<string>60.0.0</string>
		</dict>
	</array>
	<key>requires</key>
	<string>Thunderbird</string>
	<key>unattended_install</key>
	<true/>
	<key>unattended_uninstall</key>
	<false/>
	<key>uninstall_method</key>
	<string>removepackages</string>
	<key>uninstallable</key>
	<true/>
	<key>update_for</key>
	<array>
		<string>Thunderbird</string>
	</array>
	<key>version</key>
	<string>60.0.0</string>
</dict>
</plist>
```
FWIW, it's a Luggage-packed package that deploys a Tbird config file.  I always import via CLI.

**Comment by hjuutilainen** [comment]
Thanks for reporting.

Usually when something is not appearing in MunkiAdmin it’s because there was some key with different data type  than what MunkiAdmin was expecting. In your case it’s probably that `requires` should be an array of strings instead of a single string. Could you try changing that and test if the pkginfo is showing up in MunkiAdmin?

**Comment by klou** [comment]
Well, color me embarrassed.  Wrapping the contents there in the <array> tags fixed it.

I then checked my earliest version of the package -- 2013 -- and it was the same!  

I thought that makecatalogs would catch this, but I suppose it only does XML validation.  

No matter, thanks for the catch!
