### ISSUE TITLE
Removing all items from installs array does not fully remove the array

### ISSUE THREAD

**Issue by homebysix** [hjuutilainen/munkiadmin#166]
## Steps to reproduce:
1. Create an installs array and save.
2. Remove all items from the installs array and save.
3. Open pkginfo and notice that an empty installs array (`<array/>`) still exists.

## Expected behavior:
Removing all items from the installs array would result in the array being fully removed, not simply empty.

## Why this is important:
Until [this commit](https://github.com/munki/munki/commit/0bf8d5d23c9cbf8b737478c307f680269135de11), Munki treated an empty installs array as evidence of an item being installed in some cases. This could have undesirable consequences if such an item is included in a manifest as a managed_uninstall.

**Comment by hjuutilainen** [comment]
Thanks for reporting, fix will be included in the next release. I've now changed the behaviour only for `installs` array. I need to think if this is needed for other array type pkginfo keys.

**Comment by hjuutilainen** [comment]
Fixed in 1.6.0
