### ISSUE TITLE
MunkiAdmin does not load past listing the repo on 10.14

### ISSUE THREAD

**Issue by WardsParadox** [hjuutilainen/munkiadmin#167]
Attempting to use MunkiAdmin on 10.14 results in the inability to use it after it lists the repo items (doesn't matter which page it is on to list). I can't even get it to log as it locks the app up and must be force quit. Opening it results in my fans hitting top RPM as well.

**Comment by hjuutilainen** [comment]
Thanks for reporting. I’ll look into this once I get at least a VM with Mojave installed.

**Comment by hjuutilainen** [comment]
Fixed in 1.6.0
