### ISSUE TITLE
Git commit on makecatalogs

### ISSUE THREAD

**Issue by jacobtomlinson** [hjuutilainen/munkiadmin#18]
Would it be possible to have Munki Admin check to see if the munki repo is version controlled with git and if so add and commit and changes in the repo (and maybe even push to remote origin) when the makecatalogs command is run?

**Comment by n8felton** [comment]
:+1: - Adding my voice that this would be useful.

**Comment by arubdesu** [comment]
@n8felton uh, he already shipped… https://github.com/hjuutilainen/munkiadmin/releases/tag/v1.1.0

**Comment by n8felton** [comment]
Oh, nice, lol. Pinging @hjuutilainen to close issue?

**Comment by hjuutilainen** [comment]
Yep, this has been implemented :) Closing...
