### ISSUE TITLE
Feature request: Add Architectures as a column view option

### ISSUE THREAD

**Issue by homebysix** [hjuutilainen/munkiadmin#195]
Now that we're entering another period where "supported architecture" is an important software characteristic, it would be nice to have the option to see that information as an available column in the Packages view:

![image](https://user-images.githubusercontent.com/7801391/106637301-5c3c6280-6537-11eb-99a4-dfd3a4d975a4.png)

A comma-separated list of architectures (like what the catalogs column currently does) would be sufficient for my needs.

Thanks for considering!

**Comment by hjuutilainen** [comment]
This is now available in 1.8.0 beta 1
