### ISSUE TITLE
Version 1.8.0b1 instant crash because of CoreData.framework-version with macOS 10.13.6

### ISSUE THREAD

**Issue by stefanhirt** [hjuutilainen/munkiadmin#198]
Tried the new 1.8.0b1 with macOS 10.13.6.
On both macs running the latest build of 10.13.6 the app immediately crashs at the start, because the CoreData.framework version claims to be 1.0.0 instead of the minimum 300.0.0.

Crash report:
`Process:               MunkiAdmin [68195]
Path:                  /Applications/MunkiAdmin.app/Contents/MacOS/MunkiAdmin
Identifier:            com.hjuutilainen.MunkiAdmin
Version:               1.8.0b1 (1.8.0b1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MunkiAdmin [68195]
User ID:               501

Date/Time:             2021-05-10 10:20:37.087 +0200
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        3BB882AF-F557-5FD0-0AF9-5AE6CDC69D33

Time Awake Since Boot: 480000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x3] Wrong version

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreData.framework/CoreData
  Referenced from: /Applications/MunkiAdmin.app/Contents/MacOS/MunkiAdmin
  Reason: Incompatible library version: MunkiAdmin requires version 300.0.0 or later, but CoreData provides version 1.0.0

Binary Images:
       0x10a415000 -        0x10a534fff +com.hjuutilainen.MunkiAdmin (1.8.0b1 - 1.8.0b1) <241FF730-F640-34DB-AC23-7B89CF7439AC> /Applications/MunkiAdmin.app/Contents/MacOS/MunkiAdmin
       0x111644000 -        0x11168eadf  dyld (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> /usr/lib/dyld
    0x7fff32445000 -     0x7fff332a3fff  com.apple.AppKit (6.9 - 1561.61.100) <4E6EA3FA-8C2C-3B21-BFF9-6F8C458B7BE1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff346b7000 -     0x7fff346b7fff  com.apple.Cocoa (6.11 - 22) <3269BC26-0217-39FE-A600-D702656D838B> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff34a2f000 -     0x7fff34d85fef  com.apple.CoreData (120 - 851) <7361F2EA-2B7F-3259-909F-287BEB443781> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff34e6a000 -     0x7fff3530dfe7  com.apple.CoreFoundation (6.9 - 1455.300) <CB44B892-64CD-3E32-A518-6D40B1A7033F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3530f000 -     0x7fff3591ffef  com.apple.CoreGraphics (2.0 - 1161.21.5) <6451A561-3A83-37FB-AAA7-3FCE6D95C34C> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff35fe5000 -     0x7fff35fe5fff  com.apple.CoreServices (822.37 - 822.37) <CE816EF2-2B89-3F54-A5C6-D3080B1EFB00> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff36fce000 -     0x7fff37395ffb  com.apple.Foundation (6.9 - 1455.300) <0479E072-1DD0-3881-A9A2-EDAD3EE58C23> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff4026b000 -     0x7fff4026bfff  com.apple.quartzframework (1.5 - 21) <DCEB0FCC-2C32-3D02-8752-7B6FA009AB85> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff4026c000 -     0x7fff404b8ff7  com.apple.QuartzCore (1.11 - 584.64.2) <FD9A3180-479E-3DAC-9CF0-0D214C7E46A7> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff5ab62000 -     0x7fff5ab63ffb  libSystem.B.dylib (1252.50.4) <5A02016C-8F9D-3F47-8C39-AD2CD4F9F11D> /usr/lib/libSystem.B.dylib
    0x7fff5c21b000 -     0x7fff5c6097e7  libobjc.A.dylib (723) <843EFB54-EFCC-3A7C-BE11-092B6A556262> /usr/lib/libobjc.A.dylib

Model: Macmini7,1, BootROM 249.0.0.0.0, 2 processors, Intel Core i5, 2,8 GHz, 16 GB, SMC 2.24f32
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x02FE, 0x4544464232333241314D412D47442D460000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x02FE, 0x4544464232333241314D412D47442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x13B), Broadcom BCM43xx 1.0 (7.77.37.33.1a1)
Bluetooth: Version 6.0.7f22, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet Bond (bond0), Ethernet, bond0
PCI Card: pci17d3,1880, RAID Controller, Thunderbolt@196,0,0
PCI Card: ethernet, Ethernet Controller, Thunderbolt@192,0,0
PCI Card: ethernet, Ethernet Controller, Thunderbolt@192,0,1
Serial ATA Device: TS240GJDM820, 240,06 GB
USB Device: USB 3.0 Bus
USB Device: Portable SSD
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: Mac mini, Apple Inc., 26.1
Thunderbolt Device: xMac Pro Server TB2, Sonnet Technologies, Inc., 1, 25.1
`

**Comment by lrrrs** [comment]
This issue seems to occur when compiling with Xcode 12.5. Compiling the binary with Xcode 12.4 works fine. I wonder, what "bug" in Xcode this is. Can you change the required CoreData version somehow?

**Comment by vladborovtsov** [comment]
@lrrrs adding CoreData framework into linked frameworks explicitly should solve the problem

**Comment by hjuutilainen** [comment]
Thank you for the information. I've now explicitly added the CoreData.framework to the project and the latest release seems to be working again in my 10.13 test virtual machine.

Version 1.8.1 is now available from https://github.com/hjuutilainen/munkiadmin/releases/

**Comment by stefanhirt** [comment]
Thank you, now it works on my physical 10.13 machines!
