### ISSUE TITLE
Duplicating a manifest doesn't work if manifest already exists

### ISSUE THREAD

**Issue by kylevitale** [hjuutilainen/munkiadmin#24]
If I duplicate a manifest and the manifest already exists, munkiadmin prompts me to confirm I want to replace the manifest. However, choosing "replace" when prompted does not replace the manifest. Not a big deal though.

**Comment by kylevitale** [comment]
This was working, but with the latest version I don't see where to duplicate a manifest anymore.

**Comment by hjuutilainen** [comment]
Current release doesn't have this functionality at all but it will be back soon.

**Comment by hjuutilainen** [comment]
Fix will be in the next release.
