### ISSUE TITLE
Mass-assign catalog to manifests

### ISSUE THREAD

**Issue by arubdesu** [hjuutilainen/munkiadmin#27]
This was a head-scratcher of an omission, because you can mass-nest manifests by shift-clicking a list and then selecting options already, but when I try to add a catalog(which is my number 1 workflow oversight when adding manifests!)  to multiple manifests the selections don't appear. I'm asking other folks to confirm it's not just my install/setup

**Comment by hjuutilainen** [comment]
This is now implemented in 1.2.0. You can select multiple manifests, right-click and assign them to catalogs.
