### ISSUE TITLE
Data loss when editing manifests/pkginfos

### ISSUE THREAD

**Issue by arubdesu** [hjuutilainen/munkiadmin#33]
I'm happy to have caught the state of the repo in a recent git checkin, and have logging turned up for your perusal, but this was quite the Monday AM surprise, all manifests(only) were completely dumped of content. I know you're on vacation, the log file is sitting in dropbox for when you return, will send out-of-band.

**Comment by tincansandtwine** [comment]
I see that this is closed, but I am still having issues where saving a pkginfo will fail, and it will completely erase the existing pkginfo on the server. It's comforting to know that they are backed up, but it would be good if the program detected the fail and prompted to try again until it succeeds. In the current state, if I don't check, applications go missing from the MSC until I catch the missing pkginfo and replace it. I'm on the latest munkiadmin (1.1.0), latest munkitools (2.2.0.2401), with the repo on a Trusty server. Happy to provide any logs that would be useful.

**Comment by hjuutilainen** [comment]
By default, MunkiAdmin performs writes atomically which means that the data is written to a backup location and then renamed. This is the default (and recommended) behavior for Cocoa app. My best guess is that this is causing trouble with some network shares. To test this theory, I could create a special build for you tomorrow with all the write operations configured as non-atomic.

I still can not reproduce this with my test setups and test network shares but that obviously just means that I'm not seeing all the corner cases...

**Comment by tincansandtwine** [comment]
I'd certainly be willing to give it a shot. Would it still create the
backups in '*~/Library/Application Support/MunkiAdmin/pkgsinfo backups/' *?
That has saved my bacon a few times already...

**Comment by hjuutilainen** [comment]
Yes, backups are created normally.

Here's a test build for you to try: https://dl.dropboxusercontent.com/u/7637076/MunkiAdmin-1.1.0-1-g9b1e5e8.dmg

Configure MunkiAdmin to not write files atomically by running ```defaults write com.hjuutilainen.MunkiAdmin atomicWrites -bool NO``` in Terminal.app. You can also set the logging level to debug in MunkiAdmin Preferences -> Advanced section to get more details about what MunkiAdmin is doing.

**Comment by tincansandtwine** [comment]
​I'll start using the test build and let you know how it goes. I'm actually
wrapping up my setup, so not a whole lot to add any more. I'll try to make
a few changes to see if I run into the issue.​

**Comment by tincansandtwine** [comment]
I've done quite a bit of editing today, with a lot of edits to the pkginfo,
and no data loss so far. I have run into issues while working over VPN;
I'll try that and report back if anything disappears. I've already had
fewer write failure errors, though, so this is looking much better.
