### ISSUE TITLE
Feature Request: Context-menu option for adding to catalogs

### ISSUE THREAD

**Issue by klou** [hjuutilainen/munkiadmin#62]
With the testing->production workflow, it'd be nice to have a right-click context option to switch add to the appropriate catalog. 

Not essential, as it's only an extra click or two to open the actual pkginfo and make adjustments, but thought I'd throw it out there.

**Comment by hjuutilainen** [comment]
Thanks for the feature request. I'm planning to implement this exactly as you requested.

And at some point rethink the whole catalog workflow.

**Comment by klou** [comment]
What do you suggest against the catalog workflow? Or was that just a personal reminder, not a suggestion for me?

**Comment by hjuutilainen** [comment]
I meant that I need to rethink the MunkiAdmin catalog workflow :)

**Comment by hjuutilainen** [comment]
Implemented in 1.2.0
