### ISSUE TITLE
mode option (next to owner/group under Installation tab) not writing to pkginfo/saving

### ISSUE THREAD

**Issue by arubdesu** [hjuutilainen/munkiadmin#65]
Hey there, I tried "a+rx", with or without quotes, didn't seem to save to the actual pkginfo. (I was overriding bad perms from dev for MacID app's contents). Not sure if it isn't just my install.

**Comment by hjuutilainen** [comment]
This is an idiotic NSTextField default setting. The text field doesn't actually update its value until you "end editing" by changing the focus to some other text field or press return. So, if you only write the value and click the OK button, nothing gets changed. If you hit return (which will end the editing session on the text field and also hit the OK button), you'll get the changed value.

Convenient, isn't it? :)

Seriously though, I thought I had all of the text fields changed to a "continuously updates value" setting but apparently didn't. Will fix.

**Comment by arubdesu** [comment]
Glad it's something well understood! Pardon my lack of explanation about how I triggered the error state.
