### ISSUE TITLE
Support for preinstall_alert/preuninstall_alerts.

### ISSUE THREAD

**Issue by weswhet** [hjuutilainen/munkiadmin#66]
Would love to have the ability to add prinstall_alerts. For reference https://github.com/munki/munki/wiki/Pkginfo-Files#preinstall_alertpreuninstall_alert

A massive thanks for all the work you do! MunkiAdmin makes managing munki 100x easier. 

Wes.

**Comment by bartreardon** [comment]
I'd like to add my vote to this feature.

I'll also ad my thanks for munkiadmin - this tool is indispensable in my environment.

**Comment by hunty1** [comment]
If i manually add a preinstall_alert and then later make modifications to the pkginfo with munkiadmin, my preinstall_alert is wiped out :(

**Comment by hjuutilainen** [comment]
@hunty1 MunkiAdmin should not delete unsupported keys from pkginfo files. The only way that it might do so is if you simultaneously edit files with MunkiAdmin and a text editor. You should quit MunkiAdmin before doing manual edits and reopen MunkiAdmin after the files are saved.

**Comment by hunty1** [comment]
weird. didn't have the plist open with a text editor. 
manually added a preinstall alert to the pkginfo ages ago
I had a postinstall script in the pkginfo that removed the item from selfservice manifest.
updated munkiadmin and enabled the ondemand checkbox
removed the postinstall script in munki admin
opened plist to check it worked all o.k
found my preinstall alert was gone :(

maybe it was just me

**Comment by hjuutilainen** [comment]
@hunty1 Was this a onetime incident or can you reproduce this?

For everyone subscribed to this issue: support for editing preinstall_alert and preuninstall_alert will be included in the next release.

**Comment by weswhet** [comment]
This feature was implemented. Closing
