### ISSUE TITLE
AFP Share Issues

### ISSUE THREAD

**Issue by franton** [hjuutilainen/munkiadmin#67]
Hi,

I'm attempting to use munkiadmin to work on a repo mounted over an AFP share. It "seems" to be the case that munkiadmin copies the package to the repo then attempts to run makepkginfo on the remote file. This then fails because OS X installer doesn't like working on pkg's stored on network shares.

Is this the case? If so, would it be possible to change munkiadmin's behavior to run makepkginfo on the package before copying it to the repo?

**Comment by hjuutilainen** [comment]
This is the case. MunkiAdmin first copies the item and runs makepkginfo after that. Importing is going to see a makeover at some point and I was planning on addressing this ordering issue then. I'll see if there's anything I can do to easily change the order for the current import process.

**Comment by franton** [comment]
Ok in that case I'll turn up the auto uploading option in preferences and do that manually. That should be a good enough workaround for now.

**Comment by computeronix** [comment]
This appears to be working properly now with 1.2.1 :)  Thanks so much!!!
