### ISSUE TITLE
Unable to save / write to manifests

### ISSUE THREAD

**Issue by calldredge** [hjuutilainen/munkiadmin#71]
When I try to save to the manifests folder I receive: "The Operation could not be completed." "No other information is available about the problem." 

If I click Reload everything I was working on disappears, looks like nothing is saving properly.
When I reference the manifests folder and check to see if anything gets creating, nothing appears.

This is probably something stupid I did / missed

Thanks

**Comment by hjuutilainen** [comment]
Thanks for reporting. However, I'm not sure if I understood this correctly...

You have an existing repo (on local disk, SMB mount, other?) which you open in MunkiAdmin? You then edit a manifest but when saving you get the "operation could not be completed" error? Does this happen every time with every manifest or only sometimes?

MunkiAdmin writes logs in ~/Library/Logs/MunkiAdmin/. Anything useful in there? You can increase the logging level in Preferences, set it to highest and try reproducing the error while looking at the logs.

**Comment by calldredge** [comment]
Hi, 
I'm sorry, this issue does not appear to be related to munkiadmin, it seems to be permission related. The repo is local. When I reference the repository is works, however when I try to edit / add new manifests and save I receive the Operation error. This happens everytime, looks like it is admin error / perhaps permission.

Parts of the log show that it is clearly permission, not sure what I did wrong. I ran the chmod -R a+rX on /munki_repo/ :(
---Log File errors---
Can't read manifest file (null)
makelogs failed with code 1
manifest: Failed to copy to /Users/administrator/Library/Application Support/MunkiAdmin/manifests backups/20150715-134436
manifest: Error: Failed to write /Library/Server/Web/Data/Sites/Default/munki_repo/manifests/manifest
makecatalogs failed with code 1

**Comment by hjuutilainen** [comment]
Yep, looks like a permission issue. The user account that you're running MunkiAdmin with needs full read and write permissions to the munki repo.

**Comment by calldredge** [comment]
Yes! This was exactly it, Group permissions were as root not administrator that seemed to fix all my issues. Works great!!!! Thank you for your help!

**Comment by jasonpit** [comment]
yep permissions - sorted me out - thanks!

**Comment by dnsBlah** [comment]
How exactly did you fix this ? :)
