### ISSUE TITLE
New manifest editor doesn't allow catalog ordering?

### ISSUE THREAD

**Issue by gregneagle** [hjuutilainen/munkiadmin#72]
https://www.dropbox.com/s/ct987mg6lq9mx3d/Screenshot%202015-07-31%2016.09.16.png?dl=0

I can select catalogs, but how do I put them in their desired order?

**Comment by hjuutilainen** [comment]
I knew I forgot something. Will add!

**Comment by hjuutilainen** [comment]
This now fixed in 1.2.1:
https://github.com/hjuutilainen/munkiadmin/releases/tag/v1.2.1
