### ISSUE TITLE
How does the Manifest Types feature work and what does the Username parameter do?

### ISSUE THREAD

**Issue by niklasskoldmark** [hjuutilainen/munkiadmin#73]
I've tried dragging a manifest to the type name, creating folders with the names of the manifest types and selecting a manifest type and then right clicking in the white area and create a new manifest.

Awesome rewrite by the way, everything looks great!

**Comment by hjuutilainen** [comment]
Thanks for the issue report and sorry for the lack of documentation!

The manifest types are currently automatically determined by the contents of manifests. There's no way to manually make some manifest appear there. Here's how it currently works:
- Machine manifests are manifests that import other manifests but are not used as included manifests by other manifests
- Group manifests are manifests that import other manifests and are also imported by other manifests
- Profile manifests are manifests that install things and are imported by other manifests

They are defined in https://github.com/hjuutilainen/munkiadmin/blob/master/MunkiAdmin/UI%20Controllers/MAManifestsView.m#L301

**Comment by hjuutilainen** [comment]
The username is just for storing a custom username in manifest. I think this is mostly used by MunkiWebAdmin users.

I have some plans to make the manifest list columns user configurable (to display the username there too if desired) and add a display name key to manifests to make life easier for people who name manifests with MAC address or serial number.

**Comment by niklasskoldmark** [comment]
Ah, thanks for explaining that to me and for replying so fast. I used to name all my specific manifests to $serialnumber since that's what we name our 1to1 student laptops. It was a nightmare to find the right manifest so now I started naming them $username. I have a login hook that makes the first logged in user admin, this year I also made it update the ClientIdentifier in the ManagedInstalls.plist and "text 1" in the RemoteDesktop.plist with $username to make it easier to overview. Dunno why I didn't think of that before. 

Niklas Sköldmark

**Comment by bochoven** [comment]
Munkiadmin (1.2.1) seems to have troubles to detect my manifest structure. Some of the manifests don't show up in any category.

**Comment by hjuutilainen** [comment]
I think the filter predicates are a bit crude at the moment and they need refining. Can you send me any example manifests that you'd like to appear in certain sections? You can use my email if you don't want to create publicly viewable gists.

And as a side note, I'm planning to add some user configuration for those three types and also a possibility to add custom user defined queries.
