### ISSUE TITLE
New munkiadmin significantly slower at processing manifests

### ISSUE THREAD

**Issue by erikng** [hjuutilainen/munkiadmin#74]
I have approximately 5,000 manifests currently and when testing the new munkiadmin, it takes a few minutes to process through them. The prior release took around 15-20 seconds.

I'm what you would consider a very light munkiadmin user, but I noticed this immediately.

**Comment by hjuutilainen** [comment]
Thanks for reporting. There were a lot of changes in manifest scanning but I didn't notice a lag that big in my testing. 

Any way I could see your manifests?

**Comment by hjuutilainen** [comment]
Thanks for the manifests. And yes, I can confirm the problem. It all boils down to a few extra round trip queries for each manifest to support the referencing manifests feature. I should be able to optimize those quite a bit. I'll keep you posted.

**Comment by erikng** [comment]
Awesome. I used it a few times today and the new features are pretty slick.

**Comment by hjuutilainen** [comment]
Could you test if this custom build provides enough performance boost:
https://dl.dropboxusercontent.com/u/7637076/MunkiAdmin-1.2.0-2-gc1afe12.dmg

Don't put this on regular use yet but if it helps there might be 1.2.1 soon...

**Comment by erikng** [comment]
Significantly faster. If I had to guess it's faster than 1.1.0.

**Comment by erikng** [comment]
Second load took less than 5 seconds.

**Comment by erikng** [comment]
1.2.0 Release takes 4:25
1.2.1 Release takes 0:05 - 0:10

Using Mac Pro 2013 3.5 GHz 6-Core Xeon E5, 32 GB of RAM, 256 GB Flash Storage.

Incredible difference :)

**Comment by hjuutilainen** [comment]
Thanks, that's good to hear. Anything out of place? Does it resolve referencing manifests correctly?

**Comment by hjuutilainen** [comment]
It wasn't as simple as I thought but 1.2.1 release should give some nice improvements too:
https://github.com/hjuutilainen/munkiadmin/releases/tag/v1.2.1

**Comment by erikng** [comment]
Do you still want me to test those focus points?

**Comment by hjuutilainen** [comment]
No specific need at this time but keep the bug reports coming if you run into anything!
