### ISSUE TITLE
MunkiAdmin hangs after processing repo

### ISSUE THREAD

**Issue by flammable** [hjuutilainen/munkiadmin#75]
Hey, Hannes!  The new update looks great - thanks for this!

I haven't noticed any speed differences when scanning my repo...however, sometimes after scanning, MunkiAdmin beachballs.  I have to force-quit the app.  Sometimes, after reopening and trying again, it works, but sometimes it doesn't.

I just got it to hang again.  Here's what's printed in system.log:

```
8/4/15 11:54:15.460 AM MunkiAdmin[75456]: Cannot perform operation without a managed object context
8/4/15 11:54:15.461 AM MunkiAdmin[75456]: (
	0   CoreFoundation                      0x00007fff8ddf603c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8eb7176e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8ddf5eed +[NSException raise:format:] + 205
	3   AppKit                              0x00007fff9747430b -[_NSManagedProxy _managedObjectContext] + 66
	4   AppKit                              0x00007fff9747432b -[_NSManagedProxy _persistentStoreCoordinator] + 22
	5   AppKit                              0x00007fff9747439e -[_NSManagedProxy _entity] + 46
	6   AppKit                              0x00007fff97474626 -[_NSManagedProxy fetchRequestWithSortDescriptors:limit:] + 89
	7   AppKit                              0x00007fff97473e14 -[NSObjectController(NSManagedController) _executeFetch:didCommitSuccessfully:actionSender:] + 73
	8   AppKit                              0x00007fff9723f3c9 _NSSendCommitEditingSelector + 267
	9   AppKit                              0x00007fff9723f4ab -[NSController _controllerEditor:didCommit:contextInfo:] + 185
	10  CoreFoundation                      0x00007fff8dccd7bc __invoking___ + 140
	11  CoreFoundation                      0x00007fff8dccd612 -[NSInvocation invoke] + 290
	12  CoreFoundation                      0x00007fff8dd6d5c6 -[NSInvocation invokeWithTarget:] + 54
	13  Foundation                          0x00007fff9308341b __NSFireDelayedPerform + 364
	14  CoreFoundation                      0x00007fff8dd492e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff8dd48f73 __CFRunLoopDoTimer + 1059
	16  CoreFoundation                      0x00007fff8ddbc53d __CFRunLoopDoTimers + 301
	17  CoreFoundation                      0x00007fff8dd04608 __CFRunLoopRun + 2024
	18  CoreFoundation                      0x00007fff8dd03bd8 CFRunLoopRunSpecific + 296
	19  HIToolbox                           0x00007fff89ab456f RunCurrentEventLoopInMode + 235
	20  HIToolbox                           0x00007fff89ab41ee ReceiveNextEventCommon + 179
	21  HIToolbox                           0x00007fff89ab412b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	22  AppKit                              0x00007fff96eae8ab _DPSNextEvent + 978
	23  AppKit                              0x00007fff96eade58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	24  AppKit                              0x00007fff96ea3af3 -[NSApplication run] + 594
	25  AppKit                              0x00007fff96e20244 NSApplicationMain + 1832
	26  libdyld.dylib                       0x00007fff8cb565c9 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
```

I believe there are hang reports and spin reports, too, if you'd like them.

A couple of times, I've gotten as far as clicking "Recently Modified" before the app hangs.  In the instance above, the loading had just completed, but I couldn't click on anything.

Some background: I'm using MunkiAdmin over an SMB 1 share (the server supports SMB 2 and 3, but our server unmounts the share after an idle period, which drives me crazy).  Per the release notes, I preemptively applied ```defaults write com.hjuutilainen.MunkiAdmin atomicWrites -bool NO``` to my machine - I can remove that if you think it'll help.  I also had renamed my old preferences file when the prefs domain changed a couple of releases ago - I wanted to keep my defaults. :smile: 

Is there anything I can do on my end to make this easier to track down?  I really like the new manifests interface, so I'm trying to avoid downgrading.

Thank you so much!

**Comment by hjuutilainen** [comment]
Thanks for reporting. 

The non-atomic writes shouldn't be a problem when reading, the preference is only used when writing something to the repo. Could you try ruling out the network and copy the pkgsinfo, icons and manifests directories to a local folder and try opening that? Those crash reports might be valuable too.

**Comment by flammable** [comment]
Thanks, Hannes!  I copied those three directories to a test repo on my desktop.  I launched MunkiAdmin 5 times without issues.

I then copied some additional directories from the server:

catalogs
client_resources
screenshots

Opening MunkiAdmin caused it to hang again.  I then removed each directory, one at a time, and found that removing client_resources caused it to stop hanging.  Putting that directory back caused it to hang again.  I tried this for a few more times, with the same results.  Then, just as I was writing this, it stopped hanging for about 5 more times.  That directory might not be the problem after all, but I did get it to hang without the network.

[Here's the most recent spin and hang logs](https://gist.github.com/flammable/aa5f2d160d1308656817).  Is there anything else I can do to troubleshoot?

**Comment by hjuutilainen** [comment]
Yep, this is related to the slow scanning (#74) and it seems that core data is dead locking in some cases. How big is your repo, how many packages and manifests? I can easily reproduce this with a repo with thousands of manifests and packages but then again most of my ~1000 item repos work fine.

**Comment by flammable** [comment]
1.2.0 actually seems faster to me, but they upped the RAM of our Munki server at the same time - that could be why.

There are 2 catalogs, 853 manifests, 439 pkginfo files, 416 pkgs, 169 icons, and 1 zipped client_resources file in our repo.

**Comment by hjuutilainen** [comment]
Could you test if this custom build hangs after scanning:
https://dl.dropboxusercontent.com/u/7637076/MunkiAdmin-1.2.0-2-gc1afe12.dmg

Don't put this on regular use yet but if it helps there might be 1.2.1 soon...

**Comment by flammable** [comment]
Thanks, Hannes!  I haven't gotten this build to hang yet. :+1:

**Comment by hjuutilainen** [comment]
This should be fixed in 1.2.1:
https://github.com/hjuutilainen/munkiadmin/releases/tag/v1.2.1

**Comment by flammable** [comment]
Awesome!  Seriously, thank you so much!  Not a day goes by that I don't have MunkiAdmin open.

**Comment by hjuutilainen** [comment]
Thanks!
