### ISSUE TITLE
Internal Error, an uncaught exception was raised. 

### ISSUE THREAD

**Issue by weswhet** [hjuutilainen/munkiadmin#76]
![screen shot 2015-07-31 at 2 31 29 pm](https://cloud.githubusercontent.com/assets/6865785/9075807/3bcd8c48-3ace-11e5-987d-69974aa71d9d.png)

I get the above warning when opening MunkiAdmin for the first time.. Everything still seems to function properly though. I'm currently running MunkiAdmin 1.2.0 but this was present on the previous version as well and 10.11 Beta 6. The contents of the exception are below.. 

"Exception Name: NSInternalInconsistencyException
Description: Cannot perform operation without a managed object context
User Info: (null)

0   CoreFoundation                      0x00007fff9bb227dc __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff8cb03052 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff9bb2268d +[NSException raise:format:] + 205
3   AppKit                              0x00007fff8ba2e7cb -[_NSManagedProxy _managedObjectContext] + 66
4   AppKit                              0x00007fff8ba2e7eb -[_NSManagedProxy _persistentStoreCoordinator] + 22
5   AppKit                              0x00007fff8ba2e85e -[_NSManagedProxy _entity] + 46
6   AppKit                              0x00007fff8ba2e984 -[_NSManagedProxy usableSortDescriptorsFromArray:] + 104
7   AppKit                              0x00007fff8b84b192 -[NSArrayController(NSManagedController) defaultFetchRequest] + 62
8   AppKit                              0x00007fff8ba2e2d0 -[NSObjectController(NSManagedController) _executeFetch:didCommitSuccessfully:actionSender:] + 75
9   AppKit                              0x00007fff8b7d37e6 -[NSController _controllerEditor:didCommit:contextInfo:] + 185
10  CoreFoundation                      0x00007fff9b9ed9dc __invoking___ + 140
11  CoreFoundation                      0x00007fff9b9ed82e -[NSInvocation invoke] + 286
12  CoreFoundation                      0x00007fff9ba8d4e6 -[NSInvocation invokeWithTarget:] + 54
13  Foundation                          0x00007fff8941dacd __NSFireDelayedPerform + 377
14  CoreFoundation                      0x00007fff9ba694b4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
15  CoreFoundation                      0x00007fff9ba69143 __CFRunLoopDoTimer + 1075
16  CoreFoundation                      0x00007fff9bae6cda __CFRunLoopDoTimers + 298
17  CoreFoundation                      0x00007fff9ba24511 __CFRunLoopRun + 1841
18  CoreFoundation                      0x00007fff9ba23b78 CFRunLoopRunSpecific + 296
19  HIToolbox                           0x00007fff8e4863e5 RunCurrentEventLoopInMode + 235
20  HIToolbox                           0x00007fff8e486083 ReceiveNextEventCommon + 184
21  HIToolbox                           0x00007fff8e485fbb _BlockUntilNextEventMatchingListInModeWithFilter + 71
22  AppKit                              0x00007fff8b470ae7 _DPSNextEvent + 1076
23  AppKit                              0x00007fff8b83cac5 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 440
24  AppKit                              0x00007fff8b466986 -[NSApplication run] + 682
25  AppKit                              0x00007fff8b3e8e9a NSApplicationMain + 1176
26  libdyld.dylib                       0x00007fff969175ad start + 1"

**Comment by hjuutilainen** [comment]
Thanks for reporting! This is a bug I've seen many times but I just can't make it go away. It happens when you have the option selected to open previous repo automatically. The exception is harmless since the managed object context is reset after the repo is scanned but nevertheless it bothers me a lot and should be fixed. 

I need to try harder to get this resolved...

**Comment by weswhet** [comment]
Sounds good! Thanks!

**Comment by hjuutilainen** [comment]
A temporary fix for this will be included in the next release.

**Comment by hjuutilainen** [comment]
This is included in the 1.2.2 release.

**Comment by weswhet** [comment]
<3 this :)
