### ISSUE TITLE
Hitting cancel on previously opened pkginfo file removes uncommitted changes

### ISSUE THREAD

**Issue by erikng** [hjuutilainen/munkiadmin#79]
1. Open pkginfo file
2. Make changes
3. Hit okay
4. Don't commit changes
5. Open pkginfo file
6. Hit cancel/Esc.

Previously written changes are removed.

**Comment by hjuutilainen** [comment]
Thanks. Interesting bug!

**Comment by erikng** [comment]
I'm obviously using munkiadmin now. :+1:

**Comment by hjuutilainen** [comment]
This is now fixed in version 1.4.2.
