### ISSUE TITLE
Manifest Directories view does not process sub directories

### ISSUE THREAD

**Issue by erikng** [hjuutilainen/munkiadmin#83]
If you still have my manifest folder, you can see what I'm talking about.

Go to Manifest view and then Directories section.

manifests**
-->Folder1
-->Folder1.manifest (appears)
---->Folder2 (does not appear)
---->Folder2.manifest (does not appear in Folder1 view)
(continues on down the path)

Ideally it would be great if each directory could view all sub directories and manifests.

If that isn't possible, then perhaps at least list the sub directories.

**exclude the top level manifest folder from this as it would then be equivalent to "All Manifests" at the top section.

**Comment by hjuutilainen** [comment]
Subdirectories should now correctly appear in the sidebar (f241213).

There could be a preference option for recursively displaying contents for selected folder but I don't think it should be the default. I don't think any of the standard OS X apps do this by default (for example Mail.app). And for excluding the top level manifest folder from sidebar, I don't agree. It should be there even though the contents might be the same. It's needed for dragging destination.

**Comment by erikng** [comment]
Thanks. I'll test soon. 

The only reason I think the top folder should be excluded is if manifests are in there as well. It will be difficult to discern them (perhaps manifests shown in the sub folders should be a different color?) between sub manifests.

**Comment by erikng** [comment]
Actually now that I Re read your statement I think I didn't explain it properly. The top level folder should be there, but I meant it should be excluded from the recursive displaying is there could be thousands of manifests displayed. If the admin needs quick access to the manifests it may be difficult. If they want the recursive view of the entire directory they can use the top view. 

I completely agree that it needs to exist.

**Comment by hjuutilainen** [comment]
Ah, now I understand. I need to think about some ways to implement the recursive viewing. Fix for the original issue is included in 1.2.2 release.
