### ISSUE TITLE
Batch Extract Icons Hanging

### ISSUE THREAD

**Issue by tallfunnyjew** [hjuutilainen/munkiadmin#84]
Nothing happens when I click on "Extract". Status stays on "idle" as shown here. I'm on a Mac Mini running OSX 10.10.4 and server 4.1.3. This wasn't the case with the older version from a few days back. 

(love your app, BTW, so thank you!)

![screen shot 2015-08-07 at 10 51 22 am](https://cloud.githubusercontent.com/assets/2782686/9142109/6faa5386-3cf2-11e5-930b-e762dc1c3e1a.png)

**Comment by hjuutilainen** [comment]
Thanks for reporting. Does it do this every time? Anything useful in ~/Library/Logs/MunkiAdmin/? You could try increasing the logging level in preferences to get more messages in the log.

**Comment by tallfunnyjew** [comment]
Did some deeper digging via logs. Essentially, the application wasn't allowed to create the files it needed. When I changed the munki_repo folder to 777, everything started working. So as far as I'm concerned, the issue was on my end, not yours. 

Regardless, I'm having all sorts of permission issues between autopkg, autopkr, and the munki tools. I find that i have to KEEP changing the permissions of the munki_repo or things continue to malfunction. 

Love your tool: thanks for creating it for the community!

**Comment by erikng** [comment]
Do not use 777 permissions! That is not a valid solution to your problems.

**Comment by tallfunnyjew** [comment]
I'm open to your other suggestions, if you have them.

**Comment by erikng** [comment]
are you running anything as root? Come into the munki slack channel and many people can try and help you.

**Comment by tallfunnyjew** [comment]
will move discussion to slack. case closed here. thanks, all.
