### ISSUE TITLE
Catalog name not fully visible in manifest editor

### ISSUE THREAD

**Issue by mattiasvdm** [hjuutilainen/munkiadmin#87]
When double clicking on a manifest the names of the catalogs only show 13 characters. If you have two catalogs named "Microsoft Office 2011" and "Microsoft Office 2014" it's hard to figure out which is which.
![catalogs](https://cloud.githubusercontent.com/assets/8159258/9301657/5d046092-44d0-11e5-987d-cec198ee51d9.png)

**Comment by hjuutilainen** [comment]
Thanks for reporting. Will be fixed in the next release.
