### ISSUE TITLE
Feature req. - Readline support in pkginfo script modification pane

### ISSUE THREAD

**Issue by arubdesu** [hjuutilainen/munkiadmin#89]
Definitely not a high priority, as I can compose elsewhere and then copy/paste in, but I keep command-arrow-ing to get to the end/beginning of a line and instead get switched to the next pkginfo 😅 
it would be nice if whatever the regular NSText entry something-or-other keybindings worked, unless you were opposed.

**Comment by hjuutilainen** [comment]
Marked as bug since overriding the standard shortcuts is unintentional. Will fix.

**Comment by hjuutilainen** [comment]
Changed the shortcuts to cmd-N for Next and cmd-P for Previous. This restored the standard behavior in the text fields (and views). Will be included in the next release.

**Comment by hjuutilainen** [comment]
This is now fixed in version 1.4.2.
