### ISSUE TITLE
The IPv4 conditional item doesn't work properly 

### ISSUE THREAD

**Issue by niklasskoldmark** [hjuutilainen/munkiadmin#90]
Hi Hannes
When creating a conditional item for ip-address it needs to be preceded by the word 'ANY' to check all interfaces. 
This is easy to edit in the text view but it would be awesome if it was inserted automatically

**Comment by hjuutilainen** [comment]
Thank you for reporting. Will fix at some point. The condition editor is also missing some of the newer keys...

**Comment by hjuutilainen** [comment]
Fix for this is finally included in version 1.4.3.
