### ISSUE TITLE
1.3.0 - smb share upload package - plist not fully created

### ISSUE THREAD

**Issue by computeronix** [hjuutilainen/munkiadmin#92]
When using an SMB share as your repo in munki admin 1.3.0 I no longer receive an error when uploading a package (since it now generates the plist in a different step)

however the plist name that is generated automatically is (null)-(null).plist (see screenshot)
![screen shot 2015-08-31 at 9 20 54 am](https://cloud.githubusercontent.com/assets/11186939/9579562/9aa1662e-4fc1-11e5-8817-e95298ea78cd.png)

so I rename the file and then it finishes uploading.  However, the item does not appear in munki repo (even though the plist and pkg are in the repo directory).

Also the plist that is generated is not a full plist

The contents of the plist that are generated are
![screen shot 2015-08-31 at 9 23 38 am](https://cloud.githubusercontent.com/assets/11186939/9579615/ff5f0972-4fc1-11e5-9dbf-c8ac6bb73614.png)

**Comment by computeronix** [comment]
disregard it was an issue with the package file (zip) :)

DMG worked perfectly

**Comment by hjuutilainen** [comment]
Thanks for reporting and updating the issue. I think MunkiAdmin needs more error messages in cases like these. I'm also pretty sure that some of the error handling is not happening properly because I changed the process order.

**Comment by computeronix** [comment]
Well, another pkg file I attempted to upload through the SMB/AFP share also generated a null plist.  However the same pkg file uploaded locally to the server worked fine

Let me know what logs or anything you need

**Comment by computeronix** [comment]
Fixed in 1.3.1   thanks so much!

**Comment by gwinterboer** [comment]
I'm having this issue as well. What is the best method of making a DMG for the package and associated  files?

**Comment by eineLeipzigerin** [comment]
hm , I do have the same issue with (null)(null) pkginfo file not created when I import certain dmg to  my repository with munkiadmin, using macOS. When I run the munkiimport locally, I am able to create the pkginfo-file and can copy it to the repo, but it is not very elegant, and number of programs who create (null)(null) pkginfo files are raising. :-(
