### ISSUE TITLE
Invalid installs type when adding directories

### ISSUE THREAD

**Issue by nmcspadden** [hjuutilainen/munkiadmin#93]
When adding directories to the "Contents" -> "Installs" section, if you add a path manually but fill in no other attributes, you get this result in the pkginfo:  
```
	<key>installs</key>
	<array>
		<dict>
			<key>path</key>
			<string>/opt/android_sdk</string>
		</dict>
	</array>
```

Since there's no comparison key, managedsoftwareupdate reports an ERROR trying to compare an install type to nothing.  MunkiAdmin should warn against creating an invalid construction here.

**Comment by hjuutilainen** [comment]
Thanks for this. Installs items validation will be included in the next release.
