### ISSUE TITLE
git-integration

### ISSUE THREAD

**Issue by niklasskoldmark** [hjuutilainen/munkiadmin#95]
Hi Hannes
I keep all directories except pkgs and catalogs under version control and I remember from your talk at macsysadmin last year that you also git a lot of stuff.
The way we do it now is that I do packages and most of the manifests and the other stuff and I try to commit on every makecatalog. However the helpdesk-personel needs to be able to change catalogs from testing to live, add manifests and packages to manifests. They don't know how to git stuff so all the commits are done by my user in my name (or autopkg if its an automated job)
I think it would make a nice feature to be able to add, commit with commitmessage-popup and push directly from munkiadmin.

This feature could later grow to incorporate branching, merging and automated suggestions for commit message.

**Comment by bochoven** [comment]
:+1: Could you add svn support as well? Or maybe a hook that could trigger a svn commit

**Comment by hjuutilainen** [comment]
There is a built-in script support (added in 1.1.0) that could be used for something like this. From the release notes:

- Support for running custom scripts when saving
    - MunkiAdmin looks for executable files (with any extension) with the following names:
        - pkginfo-presave
        - pkginfo-postsave
        - manifest-presave
        - manifest-postsave
        - repository-presave
        - repository-postsave
    - The scripts should be saved in `<repository>/MunkiAdmin/scripts/` or `~/Library/Application Support/MunkiAdmin/scripts/`.
    - The presave scripts can abort the save by exiting with anything other than 0.
    - The pkginfo and manifest scripts are called with 2 arguments:
        - $1: Full path to the pkginfo
        - $2: File name of the pkginfo
    - All of the scripts are called with the working directory set to the current repository root.
    - See the example script below:

A quick example of a working pkginfo-postsave script which would create a git commit every time a pkginfo is edited and saved:

    #!/bin/bash

    # Use the Unofficial Bash Strict Mode
    # <http://redsymbol.net/articles/unofficial-bash-strict-mode/>
    set -euo pipefail
    IFS=$'\n\t'

    FILE_PATH=$1
    FILE_NAME=$2
    echo "Path: ${FILE_PATH}"
    echo "Name: ${FILE_NAME}"
    echo "Current working directory: $(PWD)"

    # Create a git commit
    git add "${FILE_PATH}"
    git commit -m "MunkiAdmin edited pkginfo ${FILE_NAME}"

**Comment by bochoven** [comment]
Coolness!

**Comment by niklasskoldmark** [comment]
Fantastic!


Niklas Sköldmark

**Comment by hjuutilainen** [comment]
May I take it from this that you both might be able to get the functionality you need with the current script support? :)

**Comment by niklasskoldmark** [comment]
I've got what I need and more:) I'll probably post a bug report on a related smbshare issue

Niklas Sköldmark
