### ISSUE TITLE
Manifest view changed back

### ISSUE THREAD

**Issue by cashxx** [hjuutilainen/munkiadmin#96]
This is a feature request, not sure on what others think, but I would love to see the Manifests view go back to how it was so it shows like Catalogs view with the left column and stays in the same window instead of popping up another window.  Its easier to switch between the Manifests down the left column with the Installs tab selected and quickly see what packages are set and compare the different manifests.  With version 1.3.1 you have alot more clicking to get around to see the same thing and not as easy to compare the manifests anymore.  Actually I think this changed in 1.2.0.  I was using 1.1.0 and just upgraded to 1.3.1 and switched back to 1.1.0 for now.

**Comment by arubdesu** [comment]
Can't say I agree, since you can now see inherited/included manifests, which need a different UI to support them. Try it, you'll like it 🙃

**Comment by hjuutilainen** [comment]
Thank you for the feedback. I respect your opinion but bringing back the old manifests view is something I will not even consider (thus the label "wontfix"). I will however take this as an enhancement request to make the new manifests view better.
