### ISSUE TITLE
Manifest groupings stop displaying filtered matches

### ISSUE THREAD

**Issue by arubdesu** [hjuutilainen/munkiadmin#97]
Haven't tested extensively on 1.3.x, but I find that clicking between the manifest groupings after a certain point(I notice it pretty soon after editing one) does not make it go back to the filtering it had applied, and I just see them all lumped together - the right panes contents do not hide the items outside of the grouping. Sorry this may sound a bit fuzzy, but I believe it has been reproduce-able since the Manifest overhaul.

**Comment by arubdesu** [comment]
I'm able to reproduce the issue on 1.3.1 after also switching between the pkg and manifest views

**Comment by hjuutilainen** [comment]
This is probably caused by #101. Fix coming in the next release.

**Comment by hjuutilainen** [comment]
Included now in the 1.4.0 release.
