### ISSUE TITLE
Items to Copy is uneditable

### ISSUE THREAD

**Issue by WardsParadox** [hjuutilainen/munkiadmin#99]
As soon as you go to type anything in the Items to Copy section under Installation, the window loses focus. It affects all fields under Items to Copy.

EDIT: Affects all fields sporadically but always affects Destination Path and Source Item Paths. Also shows that no changes have been made to the field but looking at the file, the one letter change has been made.

**Comment by hjuutilainen** [comment]
I can confirm this. Most likely related to a recent change about constantly updating the values in those fields. Interestingly it behaves correctly in my test builds but the release build has this...

Will fix in the next release. Thanks for reporting.

**Comment by WardsParadox** [comment]
No problemo. Thought I was going crazy when I was editing it. Kept thinking
"Don't press tab this time!" haha.
